//! Nova Proof Types and Serialization
//!
//! Defines the proof structures used in the Nova-SNARK proving system.

use ark_serialize::SerializationError;
use serde::{Deserialize, Serialize};

use super::ProofSystemId;
use crate::nf_client_proof::Proof;
use alloy::primitives::Bytes;

/// Nova Client Proof
///
/// This proof is generated by the client to prove the validity of a transaction
/// using the pure Nova proving system (typically compressed via Spartan).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NovaClientProof {
    /// Compressed SNARK proof bytes
    pub snark_proof: Vec<u8>,
}

impl NovaClientProof {
    /// Serialize the proof with the proof system ID prefix
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        // Prefix with proof system ID
        bytes.push(ProofSystemId::NovaV1 as u8);

        let proof_bytes = bincode::serialize(self)
            .map_err(|_| SerializationError::InvalidData)
            .expect("serialization should not fail");
        bytes.extend_from_slice(&proof_bytes);
        bytes
    }

    /// Deserialize a proof from bytes, validating the proof system ID prefix
    pub fn from_bytes(input_bytes: &[u8]) -> Result<Self, SerializationError> {
        if input_bytes.is_empty() {
            return Err(SerializationError::InvalidData);
        }

        let id = input_bytes[0];
        if id != ProofSystemId::NovaV1 as u8 {
            return Err(SerializationError::InvalidData);
        }

        bincode::deserialize(&input_bytes[1..]).map_err(|_| SerializationError::InvalidData)
    }
}

impl Proof for NovaClientProof {
    fn compress_proof(&self) -> Result<Bytes, SerializationError> {
        Ok(Bytes::from(self.to_bytes()))
    }

    fn from_compressed(compressed: Bytes) -> Result<Self, SerializationError> {
        Self::from_bytes(compressed.as_ref())
    }
}

/// Nova Block Proof
///
/// This is the top-level proof structure produced by the Nova rollup engine.
/// It contains both the IVC proof and the compressed SNARK proof.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NovaProof {
    /// Compressed SNARK proof bytes
    pub snark_proof: Vec<u8>,
    /// IVC state: commitments root
    pub commitments_root: Vec<u8>,
    /// IVC state: nullifiers root
    pub nullifiers_root: Vec<u8>,
    /// IVC state: historic root root
    pub historic_root_root: Vec<u8>,
    /// Number of transactions in the block
    pub transaction_count: usize,
}

impl NovaProof {
    /// Serialize the proof with the proof system ID prefix
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        // Prefix with proof system ID
        bytes.push(ProofSystemId::NovaV1 as u8);

        // Serialize the proof data using bincode (like PlonkBlockProof does)
        let proof_bytes = bincode::serialize(self)
            .map_err(|_| SerializationError::InvalidData)
            .expect("serialization should not fail");
        bytes.extend_from_slice(&proof_bytes);
        bytes
    }

    /// Deserialize a proof from bytes, validating the proof system ID prefix
    pub fn from_bytes(input_bytes: &[u8]) -> Result<Self, SerializationError> {
        if input_bytes.is_empty() {
            return Err(SerializationError::InvalidData);
        }

        let id = input_bytes[0];
        if id != ProofSystemId::NovaV1 as u8 {
            return Err(SerializationError::InvalidData);
        }

        bincode::deserialize(&input_bytes[1..]).map_err(|_| SerializationError::InvalidData)
    }

    /// Get the proof system ID for this proof type
    pub fn proof_system_id(&self) -> ProofSystemId {
        ProofSystemId::NovaV1
    }
}

impl Proof for NovaProof {
    fn compress_proof(&self) -> Result<Bytes, SerializationError> {
        Ok(Bytes::from(self.to_bytes()))
    }

    fn from_compressed(compressed: Bytes) -> Result<Self, SerializationError> {
        Self::from_bytes(compressed.as_ref())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_proof_serialization_roundtrip() {
        let proof = NovaProof {
            snark_proof: vec![1, 2, 3, 4, 5],
            commitments_root: vec![100],
            nullifiers_root: vec![200],
            historic_root_root: vec![200],
            transaction_count: 42,
        };

        let bytes = proof.to_bytes();
        assert_eq!(bytes[0], ProofSystemId::NovaV1 as u8);

        let restored = NovaProof::from_bytes(&bytes).unwrap();
        assert_eq!(restored.snark_proof, proof.snark_proof);
        assert_eq!(restored.transaction_count, proof.transaction_count);
    }

    #[test]
    fn test_proof_from_invalid_bytes() {
        // Wrong proof system ID (use PlonkV1 = 1)
        let mut bytes = vec![1u8]; // PlonkV1 prefix
        bytes.extend(vec![0u8; 100]);

        let result = NovaProof::from_bytes(&bytes);
        assert!(result.is_err());
    }

    #[test]
    fn test_proof_from_empty_bytes() {
        let result = NovaProof::from_bytes(&[]);
        assert!(result.is_err());
    }
}
