//! Full-statement parity: the native oracle must reproduce the frozen
//! transfer / withdraw / swap vectors (`vectors/statement.json`), and every
//! statement constraint must hold fail-closed.
//!
//! `vectors/statement.json` is generated by `examples/gen_statement.rs` from the
//! same `statement::scenarios` builders used here, and is also consumed by the
//! Noir tests (`noir/src/statement_vectors.nr`) and the provable circuit's
//! `Prover.toml`. Asserting the recomputed outputs against the committed file
//! catches any drift in the primitives or the framing layout.

use nightfish_honk_ref::fr_to_dec;
use nightfish_honk_ref::statement::{compute_statement, scenarios, StatementInputs};

const FROZEN: &str = include_str!("../../vectors/statement.json");

fn frozen() -> serde_json::Value {
    serde_json::from_str(FROZEN).expect("parse statement.json")
}

fn scenario<'a>(doc: &'a serde_json::Value, name: &str) -> &'a serde_json::Value {
    doc["scenarios"]
        .as_array()
        .expect("scenarios array")
        .iter()
        .find(|s| s["name"] == name)
        .unwrap_or_else(|| panic!("scenario {name} missing"))
}

fn assert_outputs_match(name: &str, inp: &StatementInputs) {
    let doc = frozen();
    let expected = &scenario(&doc, name)["outputs"];
    let t = compute_statement(inp);

    let got: Vec<String> = t.public_inputs.iter().map(fr_to_dec).collect();
    let want: Vec<String> = expected["public_inputs"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    assert_eq!(
        got.len(),
        27,
        "{name}: public-input vector must be 27 words"
    );
    assert_eq!(got, want, "{name}: framed public inputs drifted");

    let cmp = |label: &str, got: &str, key: &str| {
        assert_eq!(got, expected[key].as_str().unwrap(), "{name}: {label}");
    };
    cmp("final_root", &fr_to_dec(&t.final_root), "final_root");
    cmp("final_fee", &fr_to_dec(&t.final_fee), "final_fee");
    cmp(
        "final_deadline",
        &fr_to_dec(&t.final_deadline),
        "final_deadline",
    );
    cmp("swap_link", &fr_to_dec(&t.swap_link), "swap_link");
    cmp("swap_side", &fr_to_dec(&t.swap_side), "swap_side");

    let arr_eq = |label: &str, got: &[String], key: &str| {
        let want: Vec<String> = expected[key]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        assert_eq!(got, &want[..], "{name}: {label}");
    };
    arr_eq(
        "commitments",
        &t.commitments.iter().map(fr_to_dec).collect::<Vec<_>>(),
        "commitments",
    );
    arr_eq(
        "nullifiers",
        &t.nullifiers.iter().map(fr_to_dec).collect::<Vec<_>>(),
        "nullifiers",
    );
    arr_eq(
        "compressed_secrets",
        &t.compressed_secrets
            .iter()
            .map(fr_to_dec)
            .collect::<Vec<_>>(),
        "compressed_secrets",
    );
}

#[test]
fn transfer_statement_matches_frozen_vector() {
    assert_outputs_match("transfer", &scenarios::transfer_inputs());
}

#[test]
fn withdraw_statement_matches_frozen_vector() {
    assert_outputs_match("withdraw", &scenarios::withdraw_inputs());
}

#[test]
fn swap_statement_matches_frozen_vector() {
    assert_outputs_match("swap", &scenarios::swap_inputs());
}

#[test]
fn deposit_statement_matches_frozen_vector() {
    assert_outputs_match("deposit", &scenarios::deposit_inputs());
}

#[test]
fn transfer_conserves_value_and_fee() {
    // Spend 1000 = transfer 600 + change 400; fee path is all-zero here.
    let t = compute_statement(&scenarios::transfer_inputs());
    assert!(!t.withdraw_flag, "transfer must not set withdraw");
    assert!(!t.is_swap, "transfer must not set swap");
    assert!(!t.is_deposit, "transfer must not be a deposit");
}

#[test]
fn withdraw_zeroes_recipient_commitment_and_sets_flag() {
    let t = compute_statement(&scenarios::withdraw_inputs());
    assert!(t.withdraw_flag, "withdraw flag must be set");
    assert_eq!(
        fr_to_dec(&t.commitments[0]),
        "0",
        "withdraw must zero the recipient note commitment"
    );
}

#[test]
fn swap_sets_link_and_deadline() {
    let t = compute_statement(&scenarios::swap_inputs());
    assert!(t.is_swap, "swap flag must be set");
    assert_ne!(fr_to_dec(&t.swap_link), "0", "swap_link must be non-zero");
    assert_ne!(
        fr_to_dec(&t.final_deadline),
        "0",
        "swap must carry a deadline"
    );
}

#[test]
fn deposit_zeroes_nullifiers_and_emits_commitments() {
    let t = compute_statement(&scenarios::deposit_inputs());
    assert!(t.is_deposit, "deposit flag must be set");
    assert!(!t.withdraw_flag, "deposit must not set withdraw");
    assert!(!t.is_swap, "deposit must not set swap");
    // Deposit mode zeroes the root, fee, swap link, deadline and side.
    assert_eq!(fr_to_dec(&t.final_root), "0", "deposit must zero root");
    assert_eq!(fr_to_dec(&t.final_fee), "0", "deposit must zero fee");
    assert_eq!(fr_to_dec(&t.swap_link), "0", "deposit must zero swap_link");
    // All nullifiers are zeroed in deposit mode.
    for n in t.nullifiers.iter() {
        assert_eq!(fr_to_dec(n), "0", "deposit must zero all nullifiers");
    }
    // The two real deposit slots emit non-zero commitments; dummies stay zero.
    assert_ne!(
        fr_to_dec(&t.commitments[0]),
        "0",
        "real deposit commitment 0"
    );
    assert_ne!(
        fr_to_dec(&t.commitments[1]),
        "0",
        "real deposit commitment 1"
    );
    assert_eq!(
        fr_to_dec(&t.commitments[2]),
        "0",
        "dummy deposit commitment 2"
    );
    assert_eq!(
        fr_to_dec(&t.commitments[3]),
        "0",
        "dummy deposit commitment 3"
    );
    // The fifth compressed-secret word is the pushed zero.
    assert_eq!(
        fr_to_dec(&t.compressed_secrets[4]),
        "0",
        "deposit pushes a zero fifth public-data word"
    );
}
